### PR TITLE
Add zh_TW translation.

### PR DESCRIPTION
**Pull request by s8321414**
I add zh_TW translation , please review it! :smile:

### CODE REVIEW

**Comment by rthomsen** [comment]
It looks good, thanks :+1:

**Comment by s8321414** [comment]
I will make it better! :+1:

**Comment by rthomsen** [comment]
Can you update your translation according to the pot file or the Danish po file? I will release 1.1.0 shortly :)

**Comment by s8321414** [comment]
I will do it later!Am researching how to apply templater to translation...

**Pull request merged**
