### PR TITLE
#8: factor out color changing

### PR DESCRIPTION
**Pull request by a-detiste**
this makes the code a bit more readable before doing further changes

I added `else newcolor = Qt::black;` as a safeguard.

### CODE REVIEW

**Comment by a-detiste** [comment]
@rthomsen are you interrested in a rebase of this against current master ?

**Comment by rthomsen** [comment]
Can you explain a bit more why these units should be whitelisted?

**Comment by a-detiste** [comment]
these are unit that can never be active at the same time you have KDE running, and marking those in red let users think that something is wrong because they are inactive; and kcmsystemd users must read the whole screen to see if there are inactive units that are relevant

**Comment by rthomsen** [comment]
Let's continue discussion in Issue #8.

**Pull request closed without merging**
